image: marcoturi/ionic:latest

stages:
  - test

before_script:
  - npm install


cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

build_web:
  stage: test
  only:
      - master
  script:
    - npm run clean
    - npm run lint
    - npm run build

